name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest tests/

    - name: Set MLflow tracking URI
      run: |
        export MLFLOW_TRACKING_URI=file://$(pwd)/mlruns

    - name: Convert notebook to script and run
      run: |
        jupyter nbconvert --to script train.ipynb
        python train.py